apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: content-fetch
  name: content-fetch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: content-fetch
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: content-fetch
    spec:
      containers:
        - env:
            - name: JWT_SECRET
              value: some_secret
            - name: REDIS_URL
              value: redis://redis:6379
            - name: REST_BACKEND_ENDPOINT
              value: http://api:8080/api
            - name: VERIFICATION_TOKEN
              value: some_token
          image: sejaeger/omnivore-content-fetch:f603e4e52
          name: omnivore-content-fetch
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
