apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.45
          ports:
            - containerPort: 5775
              name: thrift-compact
            - containerPort: 5778
              name: config-http
            - containerPort: 6831
              name: thrift-binary
            - containerPort: 6832
              name: thrift-udp
            - containerPort: 16686
              name: query-http
            - containerPort: 14268
              name: collector-http
            - containerPort: 14250
              name: grpc
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9411"
