apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: migrate
  name: migrate
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: migrate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: migrate
    spec:
      containers:
        - args:
            - /bin/sh
            - ./packages/db/setup.sh
          env:
            - name: PGPASSWORD
              value: postgres
            - name: PG_DB
              value: omnivore
            - name: PG_HOST
              value: postgres
            - name: PG_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: sejaeger/omnivore-migrate:f603e4e52
          name: omnivore-migrate
      restartPolicy: Always
