apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: NEXT_PUBLIC_APP_ENV
              value: prod
            - name: NEXT_PUBLIC_BASE_URL
              value: http://localhost:3000
            - name: NEXT_PUBLIC_HIGHLIGHTS_BASE_URL
              value: http://localhost:3000
            - name: NEXT_PUBLIC_SERVER_BASE_URL
              value: http://localhost:4000
          image: sejaeger/omnivore-web:f603e4e52
          name: omnivore-web
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
