apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - args:
            - postgres
            - -c
            - wal_level=replica
            - -c
            - hot_standby=on
            - -c
            - max_wal_senders=10
            - -c
            - max_replication_slots=10
            - -c
            - hot_standby_feedback=on
          env:
            - name: PG_POOL_MAX
              value: "20"
            - name: POSTGRES_DB
              value: omnivore
            - name: POSTGRES_HOST_AUTH_METHOD
              value: |-
                scram-sha-256
                host replication all 0.0.0.0/0 md5
            - name: POSTGRES_INITDB_ARGS
              value: --auth-host=scram-sha-256
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: ankane/pgvector:v0.5.1
          livenessProbe:
            exec:
              command:
                - exit 0
            failureThreshold: 3
            periodSeconds: 2
            timeoutSeconds: 12
          name: omnivore-postgres
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
